### ISSUE TITLE
Tumblr

### ISSUE THREAD

**Issue by zmathiasz** [glasklart/hd#5505] opened 2015-04-05 03:02 UTC
**App Name:** Tumblr
**Bundle ID:** com.tumblr.tumblr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=305343404">305343404</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tumblr/id305343404?mt=8&uo=4">https://itunes.apple.com/us/app/tumblr/id305343404?mt=8&uo=4</a>
**App Version:** 12.4
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yahoo/id281970157?mt=8&uo=4">© Yahoo</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/bb/d7/0c/bbd70c4e-e74a-dfd0-9892-26ff846b0774/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![tumblr](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/50730423-6226a600-111b-11e9-931d-2639908b99dc.png)

**Comment by zmathiasz** [comment] 2015-04-05 03:03
Icon update w/Source and no existing github issue:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6995568/b0648418-db1e-11e4-8fc4-25b9a42adb44.png)
https://cloud.githubusercontent.com/assets/10950389/6995568/b0648418-db1e-11e4-8fc4-25b9a42adb44.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6995570/bd15760e-db1e-11e4-8aa0-0fa36f8ab619.png

**Comment by Trubbel** [comment] 2015-08-31 00:35
The icon has been updated.

**Comment by dreamnet** [comment] 2015-08-31 17:56
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9585972/5276fdba-501a-11e5-9c0a-457f24a0a8d3.png)
https://cloud.githubusercontent.com/assets/2068130/9585972/5276fdba-501a-11e5-9c0a-457f24a0a8d3.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9585984/6132fd90-501a-11e5-8316-72d2523de939.png

**Comment by BrokenCommander** [comment] 2016-09-26 19:23
Cleaner:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18848585/5c9b9338-842f-11e6-9fa1-92da17eaeeae.png)
https://cloud.githubusercontent.com/assets/22012363/18848585/5c9b9338-842f-11e6-9fa1-92da17eaeeae.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18848569/48b535e0-842f-11e6-8029-49f2c6ee888b.png

**Comment by XPEric** [comment] 2019-01-05 23:50
Needs update.

**Comment by XPEric** [comment] 2019-01-05 23:50
[DUPLICATE of #5505]
**App Name:** Tumblr
**Bundle ID:** com.tumblr.tumblr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=305343404">305343404</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tumblr/id305343404?mt=8&uo=4">https://itunes.apple.com/us/app/tumblr/id305343404?mt=8&uo=4</a>
**App Version:** 12.4
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yahoo/id281970157?mt=8&uo=4">© Yahoo</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/bb/d7/0c/bbd70c4e-e74a-dfd0-9892-26ff846b0774/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by XPEric** [comment] 2019-01-05 23:55
![tumblr](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/50730423-6226a600-111b-11e9-931d-2639908b99dc.png)
https://user-images.githubusercontent.com/2313873/50730423-6226a600-111b-11e9-931d-2639908b99dc.png
___
Source:
https://user-images.githubusercontent.com/2313873/50730421-5a670180-111b-11e9-81fe-4a8bf8053160.png

**Closed** 2019-01-20 11:40 UTC
