### ISSUE TITLE
Non icon request - Activator icon into theme?

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#6093] opened 2015-07-24 11:20 UTC
Hi Glasklart maintainers,

I love this Glasklart and i've used and contributed to it for some time now. Recently I fell in love with the activator icon and i was wondering if i could pull off duplicating the dynamic blur that is used by the activator icon and the folders of the default ios. I ask about it on reddit and to rpetrich himself but i didn't get any further in developing a theme as big as glasklart but with a slightly different feel to it. I found a screenshot on rpetrich's twitter account. Ryan didn't react to any mails i've send him and won't asnwer messages i've send trough reddit.

![the theme ryan and sentry_NC worked on](https://cloud.githubusercontent.com/assets/4236952/8873381/4bff2688-3206-11e5-854f-b5ec2f088820.png)

Is anybody here interested making a theme such as this? like a milky glasklart? 
You guys are my final hope seeing this theme on my phone in the future!

Thanks in advance!

**Comment by Trubbel** [comment] 2015-07-24 17:04
I'm not sure if I would use it, however, if you could provide icon template and do something like the Glasklart-community has? A Github for the theme? That would probably help the theme grow.

**Comment by dreamnet** [comment] 2015-07-24 17:16
@48296 As far as I know - it is not possibe to make a dynamic blurred icon background like Activator does with just Winterboard, ThemeLib or Anemone. You can only use a (semi-transparent) png as background.

**Comment by 48296** [comment] 2015-07-24 18:15
@Trubbel I want to provide an icon template but I haven't figured out a way to get the dynamic blur. As seen in the screenshot above rPetrich and sentry_NC figured out a way how to do this but they won't answer any of my emails.

@dreamnet I encounted that problem too. I made a bunch of testing icons in semi-transparent png files just to replicate such a icon. The dynamic blur gives the whole theme a special look and feel to it. There a a lot of tweakers using the dynamic blur in their tweaks and even activator has the blurred icon. It has to be possible don't you think?

**Comment by MagnaMike** [comment] 2015-07-24 18:16
So do we know how it works?

**Comment by Trubbel** [comment] 2015-07-24 18:17
@48296 What's the theme called?

**Comment by MagnaMike** [comment] 2015-07-24 18:24
@Trubbel The problem is there is no released theme. @48296 Wants to make one but doesn't know how because it's not released. The people that know how and showed a preview didn't release it and aren't replying to @48296.

**Comment by 48296** [comment] 2015-07-24 18:45
@MagnaMike Exactly! Don't know why there's this radio silence from the guys and i'm not shure why they didn't release the theme. what i do know is that it uses the default iOS folder blur. So if there would be a technique to get those out of ios but still using the blur it is possible to only have to make glyphs. I know because activator is the same technique. Inside the activator.app folder there's a bunch of icons used by activator in the past and ther is IconGlyph.png. if you rename that and respring the activator icon becomes a blur with the icongrid on top of it. And you can rename a glyph into IconGlyph.png and it will be used. Below are the icons as they are seen in the Explorer. and as seen when you rename/remove the iconglyph.png

![knipsel](https://cloud.githubusercontent.com/assets/4236952/8882057/9009fe96-3244-11e5-98bc-fd9da9b37bd7.PNG)

![iconglyph 2x](https://cloud.githubusercontent.com/assets/4236952/8882070/a7b06f1c-3244-11e5-95bf-196aff04294d.png)
 
![mygrid](https://cloud.githubusercontent.com/assets/4236952/8881901/849a025a-3243-11e5-8ff1-f286c28aaff5.png)

**Comment by MagnaMike** [comment] 2015-07-24 19:00
@48296 I don't have an iDevice anymore :blush:, so I can't really try to figure this out. Interesting project though!

**Comment by dreamnet** [comment] 2015-07-24 19:09
@48296 Sure, there is a way to use the IOS native blur function with an app - but I don't know any way to use the blur function with Winterboard - Winterboard simply dosen't support it. I think you need a special Cydia tweak (Winterboard plugin?) to get these blurred icon backgrounds. It really has an interesting look.

**Comment by Trubbel** [comment] 2015-07-24 22:59
I'm no expert in this but I read somewhere that if you were to delete these lines inside the Info.plist from the Activator folder,

`<key>SBIconClass</key>`
`<string>SBActivatorIcon</string>`

..you can theme the Activator icon, so for some reason I decided to add those lines to another system application and it ended up looking exactly like the Activator icon with the glyph as well.

It didn't work on applications from the App Store though, but then again, I have no idea how this works. I was just curious. Just thought I would share..

**Comment by MagnaMike** [comment] 2015-07-24 23:23
@Trubbel Can you upload a copy of the info.plist? I'd like to have a peek.

**Comment by Trubbel** [comment] 2015-07-24 23:32
@MagnaMike https://www.dropbox.com/s/370et9jqtnz6sz8/Info.rar?dl=0

**Comment by MagnaMike** [comment] 2015-07-25 00:37
@Trubbel So when you did it to a system app it ended up looking exactly like an activator icon? Or just the blurred background?

**Comment by Trubbel** [comment] 2015-07-25 00:42
@MagnaMike Exactly like it, blurred background and the glyph.

**Comment by MagnaMike** [comment] 2015-07-25 01:11
I tried reading up on this stuff but its above my level. All I know is that SBIconClass lets you change what type of icon it is (normal, bookmark, downloading, etc.) and it would seem that SBActivatorIcon is a custom class. I guess one would have to know how to make custom classes and then make one for every app you want themed.

**Comment by Trubbel** [comment] 2015-07-25 01:21
Yeah, and even if we figure it out, I don't really think it's a good idea to have (even automatically) change every application to a new class and then theme with WinterBoard for the glyphs.

Another funny thing is, if you put `SBClockApplicationIcon` instead of `SBActivatorIcon` you will see the clock hands over the current icon.

**Comment by MagnaMike** [comment] 2015-07-25 01:28
I think theres one for adding the date as well. I agree on the fact it probably is a bad idea/won't work.

**Comment by 48296** [comment] 2015-07-25 11:11
I don't think that that is the right way to get every icon themed. the default folder icon would be. You can use one for every icon and add a glyph instead of making different SCICONCLASS for every icon

**Comment by MagnaMike** [comment] 2015-07-25 11:17
I couldn't find out anything about a folder icon class.

**Comment by Trubbel** [comment] 2015-07-25 16:11
Nor could I, couldn't even find folder images, when searching through the system..

**Comment by MagnaMike** [comment] 2015-07-25 16:52
@Trubbel Because it won't be an image. It will be a blurred *area*, not an image.

**Comment by dreamnet** [comment] 2015-08-01 06:10
@48296 I don't think we can help you on this, so i'm closing this issue. Please let us know if you find out more!

**Closed by dreamnet** 2015-08-01 06:10 UTC
Labels: themeing-question
