### ISSUE TITLE
Amex

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#30] opened 2012-08-01 07:23 UTC
**App Name:** Amex
**Bundle ID:** com.americanexpress.amexservice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=362348516">362348516</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amex/id362348516?mt=8&uo=4">https://itunes.apple.com/us/app/amex/id362348516?mt=8&uo=4</a>
**App Version:** 6.12.0
**Seller:** American Express
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/american-express/id362348519?uo=4">© American Express</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/86/81/6a/86816a76-baa7-2716-aa83-7d00a829645d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/51439065-455ea680-1cb5-11e9-8374-ec3b98463b7a.png)

**Comment by zmathiasz** [comment] 2015-07-16 02:47
@dreamnet 

Updating for source:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/8714475/362c9ae4-2b43-11e5-94f2-8e4fbdc24cff.png)
https://cloud.githubusercontent.com/assets/10950389/8714475/362c9ae4-2b43-11e5-94f2-8e4fbdc24cff.png

Source:
https://cloud.githubusercontent.com/assets/10950389/8714477/4000b122-2b43-11e5-8b3e-f3d96fcf3316.png

**Comment by XPEric** [comment] 2019-01-06 00:31
Needs update.

**Comment by XPEric** [comment] 2019-01-06 00:31
[DUPLICATE of #30]
**App Name:** Amex
**Bundle ID:** com.americanexpress.amexservice
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=362348516">362348516</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amex/id362348516?mt=8&uo=4">https://itunes.apple.com/us/app/amex/id362348516?mt=8&uo=4</a>
**App Version:** 6.12.0
**Seller:** American Express
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/american-express/id362348519?uo=4">© American Express</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/86/81/6a/86816a76-baa7-2716-aa83-7d00a829645d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by XPEric** [comment] 2019-01-06 00:34
![amex](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/50730677-f0e9f180-1120-11e9-8588-2b9dbe056eff.png)
https://user-images.githubusercontent.com/2313873/50730677-f0e9f180-1120-11e9-8588-2b9dbe056eff.png

___
Source:
https://user-images.githubusercontent.com/2313873/50730675-eaf41080-1120-11e9-91fc-40f699fe4013.png

**Comment by dreamnet** [comment] 2019-01-20 12:14
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/51439065-455ea680-1cb5-11e9-8374-ec3b98463b7a.png)
https://user-images.githubusercontent.com/2068130/51439065-455ea680-1cb5-11e9-8374-ec3b98463b7a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/51439070-560f1c80-1cb5-11e9-9b01-ffb48d6f38ce.png

**Closed** 2019-01-20 18:58 UTC
