### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#491] opened 2012-11-08 13:11 UTC
**App Name:** Instagram
**Bundle ID:** com.burbn.instagram
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389801252">389801252</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instagram/id389801252?mt=8&uo=4">https://itunes.apple.com/us/app/instagram/id389801252?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** Instagram, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/instagram-inc./id389801255?uo=4>© Instagram, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/74/57/bc/7457bcd0-d454-19b4-e97e-6d0d8c401ba7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15267671/444de212-19c8-11e6-8b23-005bf4fdd772.png)

**Comment by Trubbel** [comment] 2015-10-09 08:18
Icon needs to be updated.

**Comment by dreamnet** [comment] 2015-10-11 21:41
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10419231/945be246-7071-11e5-8a97-3cacc7207079.png)
https://cloud.githubusercontent.com/assets/2068130/10419231/945be246-7071-11e5-8a97-3cacc7207079.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10419232/a3dcdf5e-7071-11e5-8b78-27c29abb32e5.png

**Comment by grkka** [comment] 2016-05-11 14:12
[DUPLICATE of #491]
**App Name:** Instagram
**Bundle ID:** com.burbn.instagram
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=389801252">389801252</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instagram/id389801252?mt=8&uo=4">https://itunes.apple.com/us/app/instagram/id389801252?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** Instagram, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/instagram-inc./id389801255?uo=4>© Instagram, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple60/v4/74/57/bc/7457bcd0-d454-19b4-e97e-6d0d8c401ba7/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment] 2016-05-11 16:45
uggh new icon is awful, but is up to you guys

**Comment by dreamnet** [comment] 2016-05-14 09:38
Going with the original...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/15267671/444de212-19c8-11e6-8b23-005bf4fdd772.png)
https://cloud.githubusercontent.com/assets/2068130/15267671/444de212-19c8-11e6-8b23-005bf4fdd772.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/15267674/53b51090-19c8-11e6-89da-cb5d05f5388e.png

**Closed** 2016-05-14 09:46 UTC
