### ISSUE TITLE
Grubhub: Local Food Delivery

### ISSUE THREAD

**Issue by Strxn** [glasklart/hd#6791] opened 2015-11-09 20:31 UTC
**App Name:** Grubhub: Local Food Delivery
**Bundle ID:** com.grubhub.search
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=302920553">302920553</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grubhub-local-food-delivery/id302920553?mt=8&uo=4">https://itunes.apple.com/us/app/grubhub-local-food-delivery/id302920553?mt=8&uo=4</a>
**App Version:** 7.22
**Seller:** GrubHub Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/grubhub-com/id302920556?uo=4">© GrubHub.com</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/f9/19/84/f919849f-6384-4fc0-73aa-52598114b5d9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/51083118-cc8ba780-1714-11e9-96ac-d0428f125e0d.png)

**Comment by dreamnet** [comment] 2015-11-10 20:53
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11075438/6d76b354-87f5-11e5-96ea-8b5966e87a36.png)
https://cloud.githubusercontent.com/assets/2068130/11075438/6d76b354-87f5-11e5-96ea-8b5966e87a36.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11075454/7c5c7a34-87f5-11e5-8b5e-9aa25fba67af.png

**Comment by XPEric** [comment] 2019-01-06 00:19
Needs update.

**Comment by XPEric** [comment] 2019-01-06 00:19
[DUPLICATE of #6791]
**App Name:** Grubhub: Local Food Delivery
**Bundle ID:** com.grubhub.search
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=302920553">302920553</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grubhub-local-food-delivery/id302920553?mt=8&uo=4">https://itunes.apple.com/us/app/grubhub-local-food-delivery/id302920553?mt=8&uo=4</a>
**App Version:** 7.21
**Seller:** GrubHub Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/grubhub-com/id302920556?uo=4">© GrubHub.com</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/46/f0/7d/46f07d34-a914-f4ef-e2f0-b0335ab0bf55/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Closed** 2019-01-20 11:35 UTC
