### ISSUE TITLE
Sunrise Calendar - An Outlook App

### ISSUE THREAD

**Issue by danielyi22** [glasklart/hd#1284] opened 2013-02-25 22:46 UTC
**App Name:** Sunrise Calendar - An Outlook App
**Bundle ID:** am.sunrise.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=599114150">599114150</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sunrise-calendar-outlook-app/id599114150?mt=8&uo=4">https://itunes.apple.com/us/app/sunrise-calendar-outlook-app/id599114150?mt=8&uo=4</a>
**App Version:** 4.21
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/55/23/35/5523359e-c63e-8383-c09c-6ce80b86ff15/mzl.kmxziigl.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9839288/570af3a8-5a75-11e5-8bd0-f69806f00504.png)

**Comment by l8er4now** [comment] 2015-09-13 15:50
Can we do an updated icon?

[DUPLICATE of #1284]
**App Name:** Sunrise Calendar - An Outlook App
**Bundle ID:** am.sunrise.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=599114150">599114150</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sunrise-calendar-outlook-app/id599114150?mt=8&uo=4">https://itunes.apple.com/us/app/sunrise-calendar-outlook-app/id599114150?mt=8&uo=4</a>
**App Version:** 4.21
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4>© Microsoft Corporation</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/55/23/35/5523359e-c63e-8383-c09c-6ce80b86ff15/mzl.kmxziigl.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment] 2015-09-13 22:13
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9839288/570af3a8-5a75-11e5-8bd0-f69806f00504.png)
https://cloud.githubusercontent.com/assets/2068130/9839288/570af3a8-5a75-11e5-8bd0-f69806f00504.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/9839293/6770a9a4-5a75-11e5-87b4-da2943fc23a4.png

**Closed** 2015-09-13 22:15 UTC
