### ISSUE TITLE
Microsoft Outlook

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5115] opened 2015-01-30 11:04 UTC
**App Name:** Microsoft Outlook
**Bundle ID:** com.microsoft.Office.Outlook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=951937596">951937596</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/microsoft-outlook/id951937596?mt=8&uo=4">https://itunes.apple.com/us/app/microsoft-outlook/id951937596?mt=8&uo=4</a>
**App Version:** 3.25.0
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?mt=8&uo=4">© Microsoft Corporation</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/9c/84/1b/9c841b67-ee01-320c-3b17-1ee9f6885964/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com microsoft Office Outlook-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58777135-1f370480-85cd-11e9-92e1-595374f8fef2.png)

**Comment by ivanov007** [comment] 2015-01-30 11:05
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5974734/5dedc492-a83d-11e4-8320-cf5522567d40.png)
https://cloud.githubusercontent.com/assets/3090247/5974734/5dedc492-a83d-11e4-8320-cf5522567d40.png
---
Source:
https://cloud.githubusercontent.com/assets/3090247/5974745/798758ee-a83d-11e4-9d7f-99d587e027dd.png

**Comment by XPEric** [comment] 2019-06-02 14:30
Needs icon update.

[DUPLICATE of #5115]
**App Name:** Microsoft Outlook
**Bundle ID:** com.microsoft.Office.Outlook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=951937596">951937596</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/microsoft-outlook/id951937596?mt=8&uo=4">https://itunes.apple.com/us/app/microsoft-outlook/id951937596?mt=8&uo=4</a>
**App Version:** 3.25.0
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?mt=8&uo=4">© Microsoft Corporation</a>
**Supported Devices:** Watch4-Watch4, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/9c/84/1b/9c841b67-ee01-320c-3b17-1ee9f6885964/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment] 2019-06-03 05:00
![com microsoft Office Outlook-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58777135-1f370480-85cd-11e9-92e1-595374f8fef2.png)
https://user-images.githubusercontent.com/2068130/58777135-1f370480-85cd-11e9-92e1-595374f8fef2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58777150-2eb64d80-85cd-11e9-82bf-8e5807b9a2b6.png

**Closed** 2019-06-03 05:18 UTC
