### ISSUE TITLE
Boxer For Gmail, Outlook, Exchange, Yahoo, Hotmail, IMAP and iCloud Email

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#2822] opened 2013-05-09 02:30 UTC
**App Name:** Boxer For Gmail, Outlook, Exchange, Yahoo, Hotmail, IMAP and iCloud Email
**Bundle ID:** com.taskbox.Taskbox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=561712083">561712083</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boxer-for-gmail-outlook-exchange/id561712083?mt=8&uo=4">https://itunes.apple.com/us/app/boxer-for-gmail-outlook-exchange/id561712083?mt=8&uo=4</a>
**App Version:** 6.0.1
**Seller:** Bodkin Software Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/taskbox/id561712086?uo=4>© Taskbox</a>
**Supported Devices:** iPhone6, iPodTouchSixthGen, iPadThirdGen4G, iPadFourthGen, iPad2Wifi, iPadThirdGen, iPadMini, iPhone5c, iPad23G, iPhone4S, iPhone5, iPhone5s, iPadMini4G, iPodTouchFifthGen, iPhone6Plus, iPadFourthGen4G
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/fe/69/c7/fe69c7b5-efb5-ed19-0f9a-f3a6b0f7517f/mzl.vmkqpbgx.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9025634/a3e350ec-390c-11e5-8cff-65cd76be7ae3.png)

**Comment by l8er4now** [comment] 2015-08-01 01:49
Can we get an updated icon?

[DUPLICATE of #2822]
**App Name:** Boxer For Gmail, Outlook, Exchange, Yahoo, Hotmail, IMAP and iCloud Email
**Bundle ID:** com.taskbox.Taskbox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=561712083">561712083</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/boxer-for-gmail-outlook-exchange/id561712083?mt=8&uo=4">https://itunes.apple.com/us/app/boxer-for-gmail-outlook-exchange/id561712083?mt=8&uo=4</a>
**App Version:** 6.0.1
**Seller:** Bodkin Software Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/taskbox/id561712086?uo=4>© Taskbox</a>
**Supported Devices:** iPodTouchSixthGen, iPhone4S, iPhone5, iPodTouchFifthGen, iPhone6, iPhone5c, iPadMini, iPadThirdGen4G, iPadFourthGen4G, iPadFourthGen, iPadThirdGen, iPhone5s, iPad2Wifi, iPad23G, iPadMini4G, iPhone6Plus
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/pf/us/r30/Purple7/v4/fe/69/c7/fe69c7b5-efb5-ed19-0f9a-f3a6b0f7517f/mzl.vmkqpbgx.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment] 2015-08-01 06:47
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9020932/c530a2a6-3829-11e5-96a3-16e7dbfc90c0.png)
https://cloud.githubusercontent.com/assets/2068130/9020932/c530a2a6-3829-11e5-96a3-16e7dbfc90c0.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9020934/d5de84ba-3829-11e5-8216-e0d85ca9c8fc.png

**Comment by dreamnet** [comment] 2015-08-02 09:50
Alternate Version:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/9025634/a3e350ec-390c-11e5-8cff-65cd76be7ae3.png)
https://cloud.githubusercontent.com/assets/2068130/9025634/a3e350ec-390c-11e5-8cff-65cd76be7ae3.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/9025635/b261167c-390c-11e5-853f-1e9f2fee8d46.png

**Closed** 2015-08-02 10:07 UTC
