### ISSUE TITLE
Google Play Movies & TV

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5847] opened 2015-06-29 08:27 UTC
**App Name:** Google Play Movies & TV
**Bundle ID:** com.google.Movies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=746894884">746894884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-play-movies-tv/id746894884?mt=8&uo=4">https://itunes.apple.com/us/app/google-play-movies-tv/id746894884?mt=8&uo=4</a>
**App Version:** 2.13.0004
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple115/v4/0c/87/d2/0c87d2e7-b794-fcd2-d0f5-05068922a1bb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/50730385-5a1a3680-111a-11e9-9b2b-368990ab5edc.png)

**Comment by Trubbel** [comment] 2015-06-29 08:28
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8403948/8531f834-1e49-11e5-9026-15cd9407f613.png)
https://cloud.githubusercontent.com/assets/10730122/8403948/8531f834-1e49-11e5-9026-15cd9407f613.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8403946/81b9ea22-1e49-11e5-89b0-b08b84dfdd2f.png

**Comment by XPEric** [comment] 2019-01-05 23:36
Needs update.

**Comment by XPEric** [comment] 2019-01-05 23:36
[DUPLICATE of #5847]
**App Name:** Google Play Movies & TV
**Bundle ID:** com.google.Movies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=746894884">746894884</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-play-movies-tv/id746894884?mt=8&uo=4">https://itunes.apple.com/us/app/google-play-movies-tv/id746894884?mt=8&uo=4</a>
**App Version:** 2.13.0004
**Seller:** Google LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-llc/id281956209?uo=4">© Google LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple115/v4/0c/87/d2/0c87d2e7-b794-fcd2-d0f5-05068922a1bb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by XPEric** [comment] 2019-01-05 23:42
![playmovies](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/50730374-b466c780-1119-11e9-8ba9-8b324ce2cf12.png)
https://user-images.githubusercontent.com/2313873/50730374-b466c780-1119-11e9-8ba9-8b324ce2cf12.png
___
Source:
https://user-images.githubusercontent.com/2313873/50730371-add85000-1119-11e9-8483-1b1c2fc45c0d.png

**Closed** 2019-01-20 11:38 UTC
