### ISSUE TITLE
Google+ - interests, communities, discovery

### ISSUE THREAD

**Issue by jfelchner** [glasklart/hd#21] opened 2012-08-01 06:07 UTC
**App Name:** Google+ - interests, communities, discovery
**Bundle ID:** com.google.GooglePlus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447119634">447119634</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google+-interests-communities/id447119634?mt=8&uo=4">https://itunes.apple.com/us/app/google+-interests-communities/id447119634?mt=8&uo=4</a>
**App Version:** 5.2.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/20/74/90/207490f8-e7ad-4888-1ea2-4031449b93a8/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12767526/ec39031c-ca09-11e5-9d56-a5c0f664a1ea.png)

**Comment by l8er4now** [comment] 2015-09-24 20:39
Got a bit of a font change, could we do an updated icon?

[DUPLICATE of #21]
**App Name:** Google+
**Bundle ID:** com.google.GooglePlus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447119634">447119634</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google+/id447119634?mt=8&uo=4">https://itunes.apple.com/us/app/google+/id447119634?mt=8&uo=4</a>
**App Version:** 4.8.6
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/google-inc./id281956209?uo=4>© Google, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/4e/27/bc/4e27bceb-ea47-6417-1236-0881317f7efe/pr_source.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment] 2015-09-24 20:52
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10086460/d2f5dcd4-630e-11e5-9656-18a48bd3ecf5.png)
https://cloud.githubusercontent.com/assets/2068130/10086460/d2f5dcd4-630e-11e5-9656-18a48bd3ecf5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10086471/e2719450-630e-11e5-84f0-3a17cd801a50.png

**Comment by ivanov007** [comment] 2015-09-24 20:55
@dreamnet wow that was fast :car: :dash:

**Comment by dreamnet** [comment] 2015-09-24 20:58
@ivanov007 Jup - :rocket:

**Comment by Trubbel** [comment] 2016-02-02 23:05
Icon needs to be updated.

**Comment by Trubbel** [comment] 2016-02-02 23:07
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/12767526/ec39031c-ca09-11e5-9d56-a5c0f664a1ea.png)
https://cloud.githubusercontent.com/assets/10730122/12767526/ec39031c-ca09-11e5-9d56-a5c0f664a1ea.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/12767525/ec36f644-ca09-11e5-8856-668ee993bd41.png

**Closed** 2016-02-03 07:23 UTC

**Comment by Christian9901** [comment] 2017-12-27 21:22
The title needs to be updated.

**Comment by dreamnet** [comment] 2017-12-27 21:26
@Christian9901 Done.
