### ISSUE TITLE
iPhone 6+

### ISSUE THREAD

**Issue by 48296** [glasklart/hd#4735] opened 2014-11-17 17:59 UTC
Hey guys any news on using the icons on a 6 plus?

**Comment by Rhokk** [comment] 2015-02-01 13:47
@dreamnet will continue our troubleshooting here.

**Comment by dreamnet** [comment] 2015-02-01 14:03
@Rhokk Jup!

**Comment by Rhokk** [comment] 2015-02-01 14:08
@dreamnet Let me know if there is a way for the iPhone to get this file without making it 0x0 - blank. Else I'll have to wait till I get back to my PC.

**Comment by dreamnet** [comment] 2015-02-01 14:21
@Rhokk That's OK, all `AppIconMask.....`-files MUST be 0x0px. These are just "dummy"-files, because Glasklart dosen't need to mask the icons.

**Comment by Rhokk** [comment] 2015-02-01 14:26
@dreamnet Ok so 0x0 for the mask is all good but I'm getting the same for all the files I try to download to my phone. I was able to use @MagnaMikes files because he zipped them. Just saving the image the normal way makes it go to the camera roll. I have safari downloader plus which lets me save to the actual directory structure however it seems like it has an issue with transparencies?

**Comment by dreamnet** [comment] 2015-02-01 14:40
@Rhokk OK, you can download a zip, containing the actual files form the master [here](http://glasklarthd.dreamnet.at/Glasklart_Test.zip). Please remove all files from `com.apple.springboard` and `com.apple.mobileicons.framework` bevore copying the ones in the zip to this folders.

**Comment by Rhokk** [comment] 2015-02-01 14:56
@dreamnet Awesome thanks for the zip! After extracting, those x3 files are correct instead of being messed up. Anyways, I emptied those two folders before moving the unzipped files over. Changed to 100% icon size and swapped to a brighter wallpaper to make it easier to see. After respringing...
 
![image](https://cloud.githubusercontent.com/assets/10787286/5992439/97137e12-a9f8-11e4-87f3-e1496a5620ab.jpg)

**Comment by MagnaMike** [comment] 2015-02-01 15:24
Hmmm... @dreamnet I think the clock icon might be the right size and everything else is too large.

**Comment by Rhokk** [comment] 2015-02-01 15:30
Ya it almost seems like the clock is very clear and the other themed icons are a tiny bit rough. Just messing around I enlarged the springboard icons to 130%...

![image](https://cloud.githubusercontent.com/assets/10787286/5992579/50a98d18-a9fd-11e4-9064-49ffc560e407.jpg)

**Comment by MagnaMike** [comment] 2015-02-01 15:35
The clock icon is 172 by 172 pixels, which I *think* is the dimensions @dreamnet made them to (180px canvas with 4px padding around icon). The other icons are 180 pixels even though they were made with the same 4px padding. It seems as if the icons are scaled up to fill the 180px area, while the clock icon, since it is a unique case, is not scaled.

**Comment by MagnaMike** [comment] 2015-02-01 15:35
Whoops! I wish there was a confirmation button asking if you were sure you want to close the issue...

**Comment by dreamnet** [comment] 2015-02-01 15:43
@MagnaMike Yes, sadly that's true. This is a bug caused by themelib. All icons themed with the IconBundles method are displayed 4px too big. There is no change if you uninstall IconBundles, so it's definetly caused by themelib. I have reported this to @coolstar [here](https://github.com/glasklart/hd/issues/5091) and he told me he will check it, but I got no answer from him so far. So we have to wait if he could solve the problem with the new Anemone app or with an update to themelib. Or we can size down all 6500 icons in the IconBundles folder..... :laughing: 
@Rhokk Thank's again for the screenshot! You have helped us a lot - I will give you extra thanks in the next release.
I don't think we can do much more at the moment.

**Comment by Rhokk** [comment] 2015-02-01 15:51
@dreamnet It's all good. I'm just happy the clock's black square got solved!

**Comment by MagnaMike** [comment] 2015-02-01 15:52
Well for now at least we could scale up the clock icon by the 4px if we wanted to, even though it is not ideal it will match the others.

**Comment by dreamnet** [comment] 2015-02-01 16:42
@MagnaMike Releasing different themes for iPhone6 and iPhone6+ is not a good idea I think. As fas as I know, the 6+ uses the normal 120x120px icons - it uses the 180x180px icons only if the user activates the zoom funtion of the 6+. So in my oppinion it would be better to provide an extra icon pack for the 6+ as I did on my website.
Scaling up the clock icon could only be a temporary solution (if we do this, we also hve to scale up the Newsstand icons) witch I don't really like. Many users dosent recognize the 4px difference on retina display. I think it's better to leve it as it is at the moment.

**Comment by MagnaMike** [comment] 2015-02-01 16:54
@dreamnet Ah, you're right - I read into it. I thought they were always 180px because I didn't know about the zoom feature. :+1:

**Comment by zmathiasz** [comment] 2015-02-16 04:15
@dreamnet @MagnaMike First time joining in. :). I am using glasklart on a 6+ and have noticed that regardless of standard or zoom view it will use the 3x icons if they are available. I also see a slight difference on transparency between the two. 

2x theme only on standard view
![](http://i.imgur.com/gZXcped.jpg)

3x theme only on standard view
![](http://i.imgur.com/RKOeyNd.jpg)

**Comment by dreamnet** [comment] 2015-02-16 06:00
@zmathiasz Welcome and yes, thats right. This is because I had to reproduce the Glasklart baseplate from scratch for the @3x icons without having the original Photoshop file from @maxrudberg. I tried to get as close as possibe to the original, but there is already a little difference. It's hard, but I will try to overwork it in the next days.

**Comment by jfelchner** [comment] 2015-02-16 19:30
@dreamnet did you contact @maxrudberg about it?  I know he's busy but I'm sure he'd give it to you.

**Comment by dreamnet** [comment] 2015-02-16 20:36
@jfelchner Actually not. Currently checking the file `sources\Baseplate\Glasklart Baseplate.psd` in our Dropbox. Maybe that's the right one...
Try to reproduce it... here is the result:
Original @2x ......... Copy @3x...
![01_glasklart_icon_template_ 2x](https://cloud.githubusercontent.com/assets/2068130/6218766/28e1233c-b622-11e4-866c-8d8d44e364dc.png)![03_glasklart_icon_template_ 3x](https://cloud.githubusercontent.com/assets/2068130/6218756/f82285a6-b621-11e4-9d5c-b7b2748369ec.png)
Na, that's not really it. It dosent look bad, but we need to match the @2x icon. Can you ask @maxrudberg for help? I'm sure he is listening more to you than to me. My last templates are [here](https://github.com/dreamnet/Glasklart_PScripts/tree/master/templates).

**Comment by jfelchner** [comment] 2015-02-17 04:34
@dreamnet I think that is it actually.  All he ever had was the the `2x` versions.  That was the last one he made. :(

**Comment by dreamnet** [comment] 2015-02-21 22:34
I gave the baseplate another try and endet up with this:
<img src="https://cloud.githubusercontent.com/assets/2068130/6315887/215fd7be-ba11-11e4-8f49-7ff988fde314.png" width="180"><img src="https://cloud.githubusercontent.com/assets/2068130/6316263/63364ed8-ba21-11e4-89b6-7624c9cfa233.png">
<img src="https://cloud.githubusercontent.com/assets/2068130/6316290/ed94a930-ba21-11e4-9e4f-092590a57647.png" width="180"><img src="https://cloud.githubusercontent.com/assets/2068130/6316291/f8a0dfa6-ba21-11e4-8114-a731fdd03c79.png">
<img src="https://cloud.githubusercontent.com/assets/2068130/6315893/472e68d4-ba11-11e4-9b29-9482ce93b1a1.png" width="180"><img src="https://cloud.githubusercontent.com/assets/2068130/6316268/8caf384c-ba21-11e4-99d6-d6aadf0e74fa.png">
The left one is the original Glasklart baseplate, just scaled up to @3x size(180x180px) for better comparsion. The right one is the rebuild baseplate in original @3x size.
It's also not 100% exact, but it's better than the one I first made. Any thoughts?

**Comment by MagnaMike** [comment] 2015-02-21 22:38
@dreamnet That looks really good to me! :+1: :+1:

**Comment by dreamnet** [comment] 2015-02-22 00:11
I must be sure that the baseplate is OK before I'm going to rebuild all @3x icons. The Photoshop file is [here](https://github.com/dreamnet/Glasklart_PScripts/tree/master/templates).

**Comment by jfelchner** [comment] 2015-02-22 00:54
@dreamnet From what I can see it looks pretty perfect. :)

Here's what they look like side-by-side with a background.

![image](https://cloud.githubusercontent.com/assets/285582/6316833/d54c6376-b9fa-11e4-8eae-da80e3dc0294.png)![image](https://cloud.githubusercontent.com/assets/285582/6316858/f13a6b46-b9fa-11e4-9832-ffd54b68a32c.png)

I think that the original when sized up has a VERY slightly thicker shadow, but I actually think I like it better the way that @dreamnet did it.

**Comment by jfelchner** [comment] 2015-02-22 01:00
@dreamnet as far as the noise is concerned, I'm not a fan of it on the icons.  If it was on the original ones, then it needs to be _drastically_ more transparent IMO than what I'm seeing here:

![image](https://cloud.githubusercontent.com/assets/285582/6316896/b15a9d56-b9fb-11e4-8bd6-d8509b811334.png)

I haven't been following closely enough so that may not even be in the repo, but I just wanted to throw that out there.  You've been doing an amazing job and I know you have things under control. :smile:

**Comment by MagnaMike** [comment] 2015-02-22 01:10
@jfelchner I'm pretty sure the noise you are taking about is just the preview background. :wink:

**Comment by dreamnet** [comment] 2015-02-22 01:12
@jfelchner Thanks for the feedback!!! Yes, the shadow of the 2x icon is a bit thicker, I have mad a 4 px drop shadow on the 3x icon, it I mad it thicker, it will go over the edges of the template.... what I could do is to make the baseplate 170x170px instead of 172x172px, so there will be one px more space for the drop shadow.... hm, I'm thinking of it.
The noise is not concerned. We are using the noise only in the preview background of the templates and for the icon preview here. It will not end up in the repo.

**Comment by jfelchner** [comment] 2015-02-22 02:33
@dreamnet :+1: you're awesome!

**Comment by jfelchner** [comment] 2015-02-22 02:34
@dreamnet, also the sized up badges look phenomenal.

**Comment by dreamnet** [comment] 2015-02-22 19:41
@jfelchner Tanks!
All @3x icons are updated with the new baseplate. Pushing out a new release in the next hours.

**Comment by jfelchner** [comment] 2015-02-23 01:39
@dreamnet I bowed out before you all switched to `IconBundles`.  How much easier is Glasklart to maintain now that you don't have to maintain the literal icon names anymore?

**Comment by dreamnet** [comment] 2015-02-23 10:19
@jfelchner Way, way, way easier! - also the script for grabbing iTunes data is very helpful. The bad thing is that [IconBundles](https://github.com/nickfrey/IconBundles) seems to be not maintained or updated anymore... :cry:
I am hoping that [Anemone](https://twitter.com/anemone_ios) will do the job in the future, it should contain all the functionality of Winterboard, IconBundles and themelib - but it's not ready to be released yet.

**Comment by dreamnet** [comment] 2015-02-26 06:49
@zmathiasz Can you please post some screenshots with the latest version of glasklart (4.14.1) installed? THX!

**Comment by zmathiasz** [comment] 2015-03-22 03:54
@dreamnet Well, I completely missed your post on here 24 days ago..Wow.  Anyhoo.  Here is a screen shot with 4.15.1 instead.  :smiley: 

2x theme only on standard view:
<img src="https://cloud.githubusercontent.com/assets/10950389/6767917/17e25e5e-d024-11e4-8c8d-df453134edf1.jpg" width="150">

3x theme only on standard view:
Some of my icons are still in the old 3x template format.  I had changed them myself to match the rest at the time since they didn't have any 3x pngs available.  imdb, ebay, books, b&n, movies and google are the old 3x, everything else is the new 3x.
<img src="https://cloud.githubusercontent.com/assets/10950389/6767916/15af354e-d024-11e4-99c6-321cd7f0659b.jpg" width="150">

**Comment by dreamnet** [comment] 2015-03-22 11:01
@zmathiasz Thanks fpr posting the screenshots! Well, I think that's the best we can do. You can always download my [@3x extra pack](http://glasklarthd.dreamnet.at/download.php), I will update it permanently. But there are currently *only* 3000+ icons are made in the @3x size.

**Comment by zmathiasz** [comment] 2015-03-23 18:40
@dreamnet I attempted to download the new .psd for the 3x icons with your updated baseplate.  I get an error in Photoshop that says the file is incorrect.  I am trying to grab the one from 
https://github.com/dreamnet/Glasklart_PScripts/tree/master/templates  Am I trying to download it wrong?  I just right clicked and picked Save Link As.  If I just click it it opens on github.. :smile:

**Comment by dreamnet** [comment] 2015-03-23 20:05
@zmathiasz The @3x icon template is only avaliable [here](https://github.com/dreamnet/Glasklart_PScripts/tree/master). You can download a zip of the master (button on the right side of the page). This zip contains all the templates in two versions, the "smart" versions are only working with Photoshop CS6 and newer.
The [@3x extra pack](http://glasklarthd.dreamnet.at/download.php) I mentioned above contains only finished @3x Glasklart icons.
What I need to make @3x icons are 1024x1024px icon sources. If you want me to add an @3x verion of a particular icon to my extra pack, please open a new issue or - if a @2x version btw issue exists - comment on the existing issue and do a normal icon contribution (with icon source).

**Comment by zmathiasz** [comment] 2015-03-23 20:15
@dreamnet  Perfect.  Sounds easy enough!  :smile: Thanks!

**Comment by zmathiasz** [comment] 2015-03-23 22:30
@dreamnet Just another curiosity question. The 3x extra pack doesn't have a themed clock or calendar. Is this on purpose since the 3x pack is just an extra to the standard theme?

**Comment by dreamnet** [comment] 2015-03-24 06:04
@zmathiasz Yes, it is on purpose. The @3x extra icon pack is an addition to the normal @2x theme. We could integrate the @3x icon in the normal theme, but (currently) it wold blow it up to over 80MB. The @3x icons for the apple native apps are in the normal theme.

**Comment by MagnaMike** [comment] 2015-07-23 21:09
Closing for now.

**Closed by MagnaMike** 2015-07-23 21:09 UTC
Labels: feature
