### ISSUE TITLE
The Sims™ FreePlay

### ISSUE THREAD

**Issue by n0mar** [glasklart/hd#1635] opened 2013-03-08 05:03 UTC
**App Name:** The Sims™ FreePlay
**Bundle ID:** com.ea.sims3deluxe.ipad.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=466966101">466966101</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/the-sims-freeplay/id466966101?mt=8&uo=4">https://itunes.apple.com/gb/app/the-sims-freeplay/id466966101?mt=8&uo=4</a>
**App Version:** 5.34.3
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/electronic-arts/id284800461?mt=8&uo=4">© Electronic Arts</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/31/c8/ad/31c8ad7e-bc07-9f9a-442b-12f748d91815/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34918337-420dae00-f951-11e7-871f-301274689f5f.png)

**Comment by Christian9901** [comment] 2018-01-14 04:05
[DUPLICATE of #1635]
**App Name:** The Sims™ FreePlay
**Bundle ID:** com.ea.sims3deluxe.ipad.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=466966101">466966101</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/the-sims-freeplay/id466966101?mt=8&uo=4">https://itunes.apple.com/gb/app/the-sims-freeplay/id466966101?mt=8&uo=4</a>
**App Version:** 5.34.3
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/electronic-arts/id284800461?mt=8&uo=4">© Electronic Arts</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/31/c8/ad/31c8ad7e-bc07-9f9a-442b-12f748d91815/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by Christian9901** [comment] 2018-01-14 04:06
Needs an update.

**Comment by dreamnet** [comment] 2018-01-14 16:35
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34918337-420dae00-f951-11e7-871f-301274689f5f.png)
https://user-images.githubusercontent.com/2068130/34918337-420dae00-f951-11e7-871f-301274689f5f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34918341-55972bc2-f951-11e7-9a9d-1014ee3cf09b.png

**Closed** 2018-01-14 17:05 UTC
