### ISSUE TITLE
helloMobil Servicewelt

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#8249] opened 2016-10-10 07:24 UTC
**App Name:** helloMobil Servicewelt
**Bundle ID:** de.hellomobil.hellomobil-Servicewelt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=774775236">774775236</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hellomobil-servicewelt/id774775236?mt=8&uo=4">https://itunes.apple.com/us/app/hellomobil-servicewelt/id774775236?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Drillisch Aktiengesellschaft
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/drillisch-ag/id774775240?uo=4>© Drillisch AG</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/47/eb/75/47eb75fc-3e64-5422-960b-54a7c04a58f9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19229113/5e75272c-8ecb-11e6-9389-0637f64c3fe8.png)

**Comment by 2Qt2beStr8** [comment] 2016-10-10 07:25
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19229113/5e75272c-8ecb-11e6-9389-0637f64c3fe8.png)
https://cloud.githubusercontent.com/assets/20930745/19229113/5e75272c-8ecb-11e6-9389-0637f64c3fe8.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19229119/6ebf56e8-8ecb-11e6-953f-162cfe4a670f.png

**Comment by dreamnet** [comment] 2016-10-10 09:13
This shold be a duplicate of #7453, but for some reason Github seems to have deleted the original issue. I don't understand why. Anyway, it's OK to open a new issue if the old one is delted.

**Closed** 2016-10-11 20:03 UTC

**Comment by dreamnet** [comment] 2018-07-28 12:34
@ivanov007 Hmmm, you are right... my fault. 🤔 Anyway, we use this issue for this app.
