### ISSUE TITLE
Appy Geek – tech news

### ISSUE THREAD

**Issue by MasteerG33k** [glasklart/hd#1691] opened 2013-03-10 14:51 UTC
**App Name:** Appy Geek – tech news
**Bundle ID:** com.mobilesrepublic.appygeek
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438922464">438922464</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/appy-geek-tech-news/id438922464?mt=8&uo=4">https://itunes.apple.com/us/app/appy-geek-tech-news/id438922464?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** News Republic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/news-republic/id349574341?uo=4>© News Republic</a>
**Supported Devices:** iPadFourthGen, iPhone4S, iPadThirdGen4G, iPhone5s, iPhone4, iPadMini, iPhone5c, iPhone-3GS, iPodTouchourthGen, iPadFourthGen4G, iPadThirdGen, iPad2Wifi, iPhone5, iPadMini4G, iPodTouchFifthGen, iPad23G
**Original Artwork:**
<img src="http://a1612.phobos.apple.com/us/r30/Purple1/v4/da/ac/a9/daaca917-396c-6845-f82e-5025f091c4dc/mzl.xotwvkct.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5671162/1d0ab66e-9786-11e4-9852-45d25efb3ea4.png)

**Comment by PolarisBeaver** [comment] 2015-01-08 07:15
I hope I do this correctly, apologies in advance if this is not the correct way of submitting an updated icon request.

**Comment by PolarisBeaver** [comment] 2015-01-08 07:15
[DUPLICATE of #1691]
**App Name:** Appy Geek – tech news
**Bundle ID:** com.mobilesrepublic.appygeek
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438922464">438922464</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/appy-geek-tech-news/id438922464?mt=8&uo=4">https://itunes.apple.com/us/app/appy-geek-tech-news/id438922464?mt=8&uo=4</a>
**App Version:** 4.3
**Seller:** News Republic
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/news-republic/id349574341?uo=4>© News Republic</a>
**Supported Devices:** iPadThirdGen4G, iPad2Wifi, iPhone4, iPhone-3GS, iPhone5, iPadFourthGen4G, iPhone4S, iPadThirdGen, iPadMini, iPhone5c, iPhone5s, iPodTouchFifthGen, iPadFourthGen, iPadMini4G, iPad23G, iPodTouchourthGen
**Original Artwork:**
<img src="http://a1612.phobos.apple.com/us/r30/Purple1/v4/da/ac/a9/daaca917-396c-6845-f82e-5025f091c4dc/mzl.xotwvkct.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by PolarisBeaver** [comment] 2015-01-08 07:17
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5659210/452c3d20-96c3-11e4-9a93-a05c10dede24.png)

**Comment by ivanov007** [comment] 2015-01-08 07:29
@PolarisBeaver thanks for the update, actually you just need to mention the icon has changed and a collaborator will update the original post, about your fulfillment, there are two things I noticed, first your image seems to be on layers, it needs to be flat on a single layer, the other thing is that you need to post the source file image on 1024x1024 format

**Comment by PolarisBeaver** [comment] 2015-01-08 07:39
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10394552/5659379/3c9a86c8-96c6-11e4-8e3a-3e52cc6a7ef2.png)

![Source Image](https://cloud.githubusercontent.com/assets/10394552/5659387/5167a34c-96c6-11e4-852f-d0623d363e24.png)

**Comment by PolarisBeaver** [comment] 2015-01-08 07:40
Sorry for the huge source preview, I thought it would be a link...

Did I fix the layer issue with the submission?

**Comment by ivanov007** [comment] 2015-01-08 07:46
@PolarisBeaver don't worry I've fixed it.
I can see it has gray in it, you need to make it all black, and maybe add some spaces between the corners to make noticeable the color change, also are you using the latest [template](http://glasklarthd.dreamnet.at/download/Glasklart_iOS7_Icon_Template.zip) for the icon?

**Comment by PolarisBeaver** [comment] 2015-01-08 07:53
Actually the grey you see is an 80% transparency of black to give the effect of a "shaded" portion of the logo to match the original icon. Is partial transparency frowned upon? First time submitting anything here, honestly.

If it makes any difference, this was done using Illustrator.

When you say you've fixed it, I am curious as to what you did so that I do not make the same mistake in the future. When I submitted the second icon, what I did was merge the visible layers and discard all other hidden layers in the PSD so I was left with a single layer, then exported with Save to Web as a png-24. I would love to learn what else I was missing to properly optimize this graphic.

**Comment by PolarisBeaver** [comment] 2015-01-08 08:04
Also yes I was using the same file, I just hash checked the one I downloaded originally with the one you linked me.

**Comment by ivanov007** [comment] 2015-01-08 09:30
@PolarisBeaver seems you have it all, you just need to make the layer 100% opaque, no transparency is allowed for the icons, instead of the transparency you can stroke a line (and delete it) over the joints to make the color difference effect

**Comment by dreamnet** [comment] 2015-01-08 21:33
@PolarisBeaver Something like this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5671162/1d0ab66e-9786-11e4-9852-45d25efb3ea4.png)
https://cloud.githubusercontent.com/assets/2068130/5671162/1d0ab66e-9786-11e4-9852-45d25efb3ea4.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5671184/311fc6a8-9786-11e4-9c0c-dceca4f837d1.png

**Comment by PolarisBeaver** [comment] 2015-01-09 02:51
Oh! I didn't get to this reply sooner, but yeah that works, feel free to use it in the theme, thanks for the feedback, I'll be submitting more icons later, with all the info I learned here in mind :)

**Comment by dreamnet** [comment] 2015-01-09 06:38
@PolarisBeaver :+1:

**Closed** 2015-01-09 19:15 UTC
