### ISSUE TITLE
Rakuten Ebates: Earn Cash Back

### ISSUE THREAD

**Issue by jpokorny2** [glasklart/hd#7588] opened 2016-07-15 14:15 UTC
**App Name:** Rakuten Ebates: Earn Cash Back
**Bundle ID:** com.ebates.EbatesMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=723134859">723134859</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/rakuten-ebates-earn-cash-back/id723134859?uo=4">https://apps.apple.com/us/app/rakuten-ebates-earn-cash-back/id723134859?uo=4</a>
**App Version:** 5.13.0
**Seller:** Ebates Shopping.com, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/ebates/id723134862?uo=4">© Ebates</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/ed/72/59/ed7259c7-3c52-f37a-0d92-a6b0a1c20b3b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58844001-2993e580-8643-11e9-806e-410535c135d0.png)

**Comment by dreamnet** [comment] 2016-07-16 03:10
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16892441/77f05b6e-4b13-11e6-8d53-c52b9a03ed46.png)
https://cloud.githubusercontent.com/assets/2068130/16892441/77f05b6e-4b13-11e6-8d53-c52b9a03ed46.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16892443/870c2178-4b13-11e6-9d10-d1f127e38fe1.png

**Comment by XPEric** [comment] 2019-01-05 23:57
Needs update.

**Comment by XPEric** [comment] 2019-01-05 23:57
[DUPLICATE of #7588]
**App Name:** Ebates: Cash Back Shopping
**Bundle ID:** com.ebates.EbatesMobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=723134859">723134859</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ebates-cash-back-shopping/id723134859?mt=8&uo=4">https://itunes.apple.com/us/app/ebates-cash-back-shopping/id723134859?mt=8&uo=4</a>
**App Version:** 4.38.6
**Seller:** Ebates Shopping.com, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ebates/id723134862?uo=4">© Ebates</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/34/9f/00/349f008a-9c83-3264-30c0-791eb5366e56/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by XPEric** [comment] 2019-01-06 00:15
![ebates](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/50730569-3bb63a00-111e-11e9-9a4b-425671f80ea4.png)
https://user-images.githubusercontent.com/2313873/50730569-3bb63a00-111e-11e9-9a4b-425671f80ea4.png

___
Source:
![ebates-src](https://user-images.githubusercontent.com/2313873/50730571-4e307380-111e-11e9-9770-c8b9d90d7942.png)

**Comment by XPEric** [comment] 2019-06-04 00:28
This icon needs to be updated, but it appears they're using the supportsAlternateIcons API to change it, as the iTunes/App Store icon hasn't changed.

**Comment by XPEric** [comment] 2019-06-04 01:04
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58844001-2993e580-8643-11e9-806e-410535c135d0.png)
https://user-images.githubusercontent.com/2313873/58844001-2993e580-8643-11e9-806e-410535c135d0.png

___
Source:
https://user-images.githubusercontent.com/2313873/58843997-24369b00-8643-11e9-8f59-836f33c4c39b.png

**Comment by dreamnet** [comment] 2019-06-07 17:46
@XPEric I think the [existing icon](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.ebates.EbatesMobile-large.png) is fine.

**Comment by dreamnet** [comment] 2019-06-07 18:11
@XPEric On second thought: You are right, this needs an update.
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59124552-4fc9c600-8960-11e9-81d5-b1315875d88c.png)
https://user-images.githubusercontent.com/2068130/59124552-4fc9c600-8960-11e9-81d5-b1315875d88c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59124580-5eb07880-8960-11e9-902e-aeb6497183ec.png

**Comment by XPEric** [comment] 2019-07-23 02:54
Needs new icon

**Comment by XPEric** [comment] 2019-07-23 02:54
![ico](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58844001-2993e580-8643-11e9-806e-410535c135d0.png)
https://user-images.githubusercontent.com/2313873/58844001-2993e580-8643-11e9-806e-410535c135d0.png

___
Source:
https://user-images.githubusercontent.com/2313873/58843997-24369b00-8643-11e9-8f59-836f33c4c39b.png

**Closed** 2019-07-27 09:04 UTC
