### ISSUE TITLE
T-Mobile

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#5372] opened 2015-03-19 04:24 UTC
**App Name:** T-Mobile
**Bundle ID:** com.tmobile.TMOAccess
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=561625752">561625752</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/t-mobile/id561625752?mt=8&uo=4">https://itunes.apple.com/us/app/t-mobile/id561625752?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** T-Mobile USA, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/t-mobile/id525560781?uo=4">© T-Mobile</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/00/14/6d/00146d33-c863-3878-5134-4290fa7304e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/51082684-ac57ea80-170c-11e9-9502-09568a58580d.png)

**Comment by WaterTrooper** [comment] 2015-03-19 04:25
Anyone want to join my family plan. 😉

**Comment by Trubbel** [comment] 2015-03-19 08:39
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/6726796/c0af39ae-ce1b-11e4-99d1-9553aaabf326.png)
https://cloud.githubusercontent.com/assets/10730122/6726796/c0af39ae-ce1b-11e4-99d1-9553aaabf326.png

Source:
https://cloud.githubusercontent.com/assets/10730122/6726789/b4e91cca-ce1b-11e4-9269-70ccd699183e.png

**Comment by dreamnet** [comment] 2015-03-19 16:03
@Trubbel Good, I just made some small corrections and the lines between the objects a bit thicker so that they can be seen on retina display - also I think this must be alligned to the right.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6734654/a9059a30-ce59-11e4-8367-a5b9358982ba.png)
https://cloud.githubusercontent.com/assets/2068130/6734654/a9059a30-ce59-11e4-8367-a5b9358982ba.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/6734660/bc07fb6e-ce59-11e4-949f-b9d7d66343be.png

**Comment by Trubbel** [comment] 2015-03-19 16:44
Yeah that does look much better, thanks!

**Comment by XPEric** [comment] 2019-01-02 21:36
Needs update

**Comment by XPEric** [comment] 2019-01-02 21:37
[DUPLICATE of #5372]
**App Name:** T-Mobile
**Bundle ID:** com.tmobile.TMOAccess
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=561625752">561625752</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/t-mobile/id561625752?mt=8&uo=4">https://itunes.apple.com/us/app/t-mobile/id561625752?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** T-Mobile USA, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/t-mobile/id525560781?uo=4">© T-Mobile</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/00/14/6d/00146d33-c863-3878-5134-4290fa7304e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment] 2019-01-03 17:51
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/50652988-6cfd0180-0f88-11e9-93c2-8f051efa1fce.png)
https://user-images.githubusercontent.com/20930745/50652988-6cfd0180-0f88-11e9-93c2-8f051efa1fce.png

Source:
https://user-images.githubusercontent.com/20930745/50653022-830ac200-0f88-11e9-9a97-47b178a7ec5f.png

**Closed** 2019-01-20 11:42 UTC
