### ISSUE TITLE
PayPal Here - Point of Sale

### ISSUE THREAD

**Issue by khattakr** [glasklart/hd#1887] opened 2013-03-18 20:07 UTC
**App Name:** PayPal Here - Point of Sale
**Bundle ID:** com.paypal.here
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=505911015">505911015</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paypal-here-point-of-sale/id505911015?mt=8&uo=4">https://itunes.apple.com/us/app/paypal-here-point-of-sale/id505911015?mt=8&uo=4</a>
**App Version:** 3.6.6
**Seller:** PayPal, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/paypal-inc/id283646712?mt=8&uo=4">© PayPal, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/43/ce/48/43ce487f-4083-bb45-4734-67add70ddf2a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59099871-b29d6c00-8924-11e9-90eb-ff2f497c1121.png)

**Comment by Trubbel** [comment] 2016-02-29 22:50
Icon needs to be updated.

**Comment by Trubbel** [comment] 2016-02-29 22:51
Icon needs an update.

**Comment by dreamnet** [comment] 2016-03-01 06:14
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13419301/2bb8cd28-df7d-11e5-981c-8487e0904c29.png)
https://cloud.githubusercontent.com/assets/2068130/13419301/2bb8cd28-df7d-11e5-981c-8487e0904c29.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13419308/3bb142dc-df7d-11e5-8c61-4ba34e33175e.png

**Comment by XPEric** [comment] 2019-06-02 14:24
Needs name and icon update.

[DUPLICATE of #1887]
**App Name:** PayPal Here - Point of Sale
**Bundle ID:** com.paypal.here
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=505911015">505911015</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paypal-here-point-of-sale/id505911015?mt=8&uo=4">https://itunes.apple.com/us/app/paypal-here-point-of-sale/id505911015?mt=8&uo=4</a>
**App Version:** 3.6.6
**Seller:** PayPal, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/paypal-inc/id283646712?mt=8&uo=4">© PayPal, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/43/ce/48/43ce487f-4083-bb45-4734-67add70ddf2a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment] 2019-06-07 11:04
?
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59099871-b29d6c00-8924-11e9-90eb-ff2f497c1121.png)
https://user-images.githubusercontent.com/20930745/59099871-b29d6c00-8924-11e9-90eb-ff2f497c1121.png

Source:
https://user-images.githubusercontent.com/20930745/59099873-b3ce9900-8924-11e9-97ae-cb17f78d63ca.png

**Closed** 2019-06-07 17:47 UTC
