### ISSUE TITLE
Zendesk Sell

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#7622] opened 2016-07-29 00:39 UTC
**App Name:** Zendesk Sell
**Bundle ID:** com.futuresimple.Base
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=488534576">488534576</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/zendesk-sell/id488534576?uo=4">https://apps.apple.com/us/app/zendesk-sell/id488534576?uo=4</a>
**App Version:** 5.1.2
**Seller:** Future Simple
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/future-simple/id488534579?uo=4">© Future Simple</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/a9/15/c2/a915c260-58a2-5ec7-1bfb-2687cbaff9ab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83967505-66339600-a8c2-11ea-8d37-bbe3a007a081.png)

**Comment by dreamnet** [comment] 2016-07-30 04:19
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17268061/6c9c9d4e-561d-11e6-8e96-283d0e49d035.png)
https://cloud.githubusercontent.com/assets/2068130/17268061/6c9c9d4e-561d-11e6-8e96-283d0e49d035.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17268063/7de83a7c-561d-11e6-928b-04457faea560.png

**Comment by popitre** [comment] 2020-05-31 16:20
[DUPLICATE of #7622]
**App Name:** Zendesk Sell
**Bundle ID:** com.futuresimple.Base
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=488534576">488534576</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/zendesk-sell/id488534576?uo=4">https://apps.apple.com/us/app/zendesk-sell/id488534576?uo=4</a>
**App Version:** 5.1.2
**Seller:** Future Simple
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/future-simple/id488534579?uo=4">© Future Simple</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/a9/15/c2/a915c260-58a2-5ec7-1bfb-2687cbaff9ab/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment] 2020-06-07 11:26
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83967505-66339600-a8c2-11ea-8d37-bbe3a007a081.png)
https://user-images.githubusercontent.com/2068130/83967505-66339600-a8c2-11ea-8d37-bbe3a007a081.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83967509-78153900-a8c2-11ea-8273-da1dc40295c9.png

**Closed** 2020-06-07 11:29 UTC

**Comment by popitre** [comment] 2020-06-07 19:30
Icon does not update with bundle ID renaming ?
