### ISSUE TITLE
TV 2 Play

### ISSUE THREAD

**Issue by madsser** [glasklart/hd#2509] opened 2013-04-16 18:33 UTC
**App Name:** TV 2 Play
**Bundle ID:** dk.tv2.play
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=515236434">515236434</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/tv-2-play/id515236434?uo=4">https://apps.apple.com/us/app/tv-2-play/id515236434?uo=4</a>
**App Version:** 3.1.5
**Seller:** TV 2 Danmark A/S
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tv-2-danmark-a-s/id431851124?uo=4">© TV 2 Danmark A/S</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/08/9e/71/089e7198-73f0-e1a5-9e6f-7f7831a01531/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/67156049-0def5a00-f31a-11e9-90da-7ddcf1ff259a.png)

**Comment by 2Qt2beStr8** [comment] 2016-11-06 14:49
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20038699/8a356bec-a438-11e6-96ee-a78c0b59adcc.png)
https://cloud.githubusercontent.com/assets/20930745/20038699/8a356bec-a438-11e6-96ee-a78c0b59adcc.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20038704/a07ef94a-a438-11e6-9181-a4554fa8061b.png

**Comment by cassio299** [comment] 2019-10-13 00:38
[DUPLICATE of #2509]
**App Name:** TV 2 Play
**Bundle ID:** dk.tv2.play
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=515236434">515236434</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/tv-2-play/id515236434?uo=4">https://apps.apple.com/us/app/tv-2-play/id515236434?uo=4</a>
**App Version:** 3.1.5
**Seller:** TV 2 Danmark A/S
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/tv-2-danmark-a-s/id431851124?uo=4">© TV 2 Danmark A/S</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**

<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/08/9e/71/089e7198-73f0-e1a5-9e6f-7f7831a01531/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**

\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by cassio299** [comment] 2019-10-13 00:40
@dreamnet New Icon request

**Comment by 2Qt2beStr8** [comment] 2019-10-18 12:17
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/67093412-e67d7d80-f1b1-11e9-8bc6-f32411015776.png)
https://user-images.githubusercontent.com/20930745/67093412-e67d7d80-f1b1-11e9-8bc6-f32411015776.png

Source:
https://user-images.githubusercontent.com/20930745/67093415-e7aeaa80-f1b1-11e9-8939-029fecd477d0.png

**Closed** 2019-10-20 07:24 UTC
