### ISSUE TITLE
Yahoo Fantasy Football & more - Daily + Full Season Football, Baseball, Basketball, Hockey

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#2978] opened 2013-05-29 05:12 UTC
**App Name:** Yahoo Fantasy Football & more - Daily + Full Season Football, Baseball, Basketball, Hockey
**Bundle ID:** com.yahoo.ffootball2009
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=328415391">328415391</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yahoo-fantasy-football-more/id328415391?mt=8&uo=4">https://itunes.apple.com/us/app/yahoo-fantasy-football-more/id328415391?mt=8&uo=4</a>
**App Version:** 7.3.1
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yahoo/id281970157?mt=8&uo=4>© Yahoo</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/fd/3b/6b/fd3b6b75-6f6e-7e85-7901-d148dabee956/mzl.qpnukzfj.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9839152/76c46812-5a36-11e5-8571-fb190322e691.png)

**Comment by l8er4now** [comment] 2015-09-13 15:51
Can we do an updated icon?

[DUPLICATE of #2978]
**App Name:** Yahoo Fantasy Football & more - Daily + Full Season Football, Baseball, Basketball, Hockey
**Bundle ID:** com.yahoo.ffootball2009
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=328415391">328415391</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yahoo-fantasy-football-more/id328415391?mt=8&uo=4">https://itunes.apple.com/us/app/yahoo-fantasy-football-more/id328415391?mt=8&uo=4</a>
**App Version:** 7.3.1
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/yahoo/id281970157?mt=8&uo=4>© Yahoo</a>
**Supported Devices:** iPhone, iPod-touch, iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple5/v4/fd/3b/6b/fd3b6b75-6f6e-7e85-7901-d148dabee956/mzl.qpnukzfj.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment] 2015-09-13 21:43
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/9839152/76c46812-5a36-11e5-8571-fb190322e691.png)
https://cloud.githubusercontent.com/assets/3090247/9839152/76c46812-5a36-11e5-8571-fb190322e691.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/9839153/76c4d054-5a36-11e5-8070-dd56447780bd.png

**Closed** 2015-09-13 21:48 UTC
