### ISSUE TITLE
Coinbase – Buy & sell Bitcoin

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#5050] opened 2015-01-12 10:58 UTC
**App Name:** Coinbase – Buy & sell Bitcoin
**Bundle ID:** com.vilcsak.bitcoin2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=886427730">886427730</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/coinbase-buy-sell-bitcoin/id886427730?mt=8&uo=4">https://itunes.apple.com/us/app/coinbase-buy-sell-bitcoin/id886427730?mt=8&uo=4</a>
**App Version:** 5.9.2
**Seller:** Coinbase, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/coinbase-inc/id588530553?mt=8&uo=4">© Coinbase, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/ed/8f/c4/ed8fc430-8447-b23b-0689-626cceb24341/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58764009-9edbb980-8562-11e9-9f28-8e2ab17f9790.png)

**Comment by andreolidavide** [comment] 2015-01-13 20:30
Is this ok?
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10515074/5728511/18855a8e-9b6b-11e4-89d3-b4be153cd763.png)

Source
https://cloud.githubusercontent.com/assets/10515074/5728537/3f6482d8-9b6b-11e4-933f-dd6904ced2de.png

**Comment by dreamnet** [comment] 2015-01-13 23:18
@andreolidavide Not bad, but I think you have forgotten to apply the Glasklart style in the finished icon and the icon in the source file is too small. Compare it with mine to see what I mean:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5731352/be32f326-9b82-11e4-9eb7-e60d769f4036.png)
https://cloud.githubusercontent.com/assets/2068130/5731352/be32f326-9b82-11e4-9eb7-e60d769f4036.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5731362/cd219a40-9b82-11e4-8c55-a4769c4da8b5.png

**Comment by XPEric** [comment] 2019-06-02 14:18
Needs name and icon update.

[DUPLICATE of #5050]
**App Name:** Coinbase – Buy & sell Bitcoin
**Bundle ID:** com.vilcsak.bitcoin2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=886427730">886427730</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/coinbase-buy-sell-bitcoin/id886427730?mt=8&uo=4">https://itunes.apple.com/us/app/coinbase-buy-sell-bitcoin/id886427730?mt=8&uo=4</a>
**App Version:** 5.9.2
**Seller:** Coinbase, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/coinbase-inc/id588530553?mt=8&uo=4">© Coinbase, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/ed/8f/c4/ed8fc430-8447-b23b-0689-626cceb24341/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by XPEric** [comment] 2019-06-02 14:22
![tyt](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58762685-3e2b8d00-8520-11e9-8ce6-471f923509f4.png)
https://user-images.githubusercontent.com/2313873/58762685-3e2b8d00-8520-11e9-8ce6-471f923509f4.png

___
Source:
https://user-images.githubusercontent.com/2313873/58762677-323fcb00-8520-11e9-8b92-10d3eba55d44.png

**Comment by dreamnet** [comment] 2019-06-02 16:17
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58764009-9edbb980-8562-11e9-9f28-8e2ab17f9790.png)
https://user-images.githubusercontent.com/2068130/58764009-9edbb980-8562-11e9-9f28-8e2ab17f9790.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58764022-b0bd5c80-8562-11e9-901b-6bf7a411c528.png

**Closed** 2019-06-02 16:57 UTC
