### ISSUE TITLE
GIF Keyboard

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#5089] opened 2015-01-23 10:46 UTC
**App Name:** GIF Keyboard
**Bundle ID:** com.riffsy.RiffsyKeyboard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=917932200">917932200</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gif-keyboard/id917932200?mt=8&uo=4">https://itunes.apple.com/us/app/gif-keyboard/id917932200?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Riffsy, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/riffsy-inc/id917932199?uo=4>© Riffsy, Inc</a>
**Supported Devices:** iPhone5c, iPhone6Plus, iPadThirdGen4G, iPadMini, iPad2Wifi, iPadThirdGen, iPadFourthGen, iPadFourthGen4G, iPhone6, iPhone5, iPadMini4G, iPad23G, iPhone4S, iPodTouchFifthGen, iPhone5s
**Original Artwork:**
<img src="http://a1109.phobos.apple.com/us/r30/Purple1/v4/27/92/b7/2792b715-213f-a462-bbd0-2468e9eb6f5e/mzl.gwwqkdjg.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5873331/d1a73978-a2ba-11e4-8a90-95008ac9364d.png)

**Comment by ivanov007** [comment] 2015-01-23 10:47
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/5873331/d1a73978-a2ba-11e4-8a90-95008ac9364d.png)
https://cloud.githubusercontent.com/assets/3090247/5873331/d1a73978-a2ba-11e4-8a90-95008ac9364d.png
Source:
https://cloud.githubusercontent.com/assets/3090247/5873338/e430cac8-a2ba-11e4-8130-b119d982a9ce.png

**Comment by grkka** [comment] 2016-02-16 12:27
Update icone, please. 
[DUPLICATE of #5089]
**App Name:** GIF Keyboard
**Bundle ID:** com.riffsy.RiffsyKeyboard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=917932200">917932200</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gif-keyboard/id917932200?mt=8&uo=4">https://itunes.apple.com/us/app/gif-keyboard/id917932200?mt=8&uo=4</a>
**App Version:** 2.5
**Seller:** Riffsy, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/riffsy-inc/id917932199?uo=4>© Riffsy, Inc</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/0f/42/fa/0f42fa00-9e30-daf9-ea4e-66556627f9b2/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment] 2016-02-17 05:25
...is it worth to do this update?

**Comment by Trubbel** [comment] 2016-02-17 05:27
Is this not just a temporary icon?

**Comment by dreamnet** [comment] 2016-02-17 05:45
Yeah, I think so, because the description of version 2.5 says "- Awesome new GIFs from #KungFuPanda"...

**Comment by dreamnet** [comment] 2016-02-17 06:50
@grkka Thats's defintly just a temporary icon, I'm pretty sure it changes (again) with the next update of this app, so we don't update the Glasklart icon.

**Comment by grkka** [comment] 2016-02-17 07:44
Ok, Thanks!

**Closed** 2016-02-17 08:47 UTC
