### ISSUE TITLE
Deezer: Music & Podcast Player

### ISSUE THREAD

**Issue by lauwaet** [glasklart/hd#3935] opened 2014-02-18 21:10 UTC
**App Name:** Deezer: Music & Podcast Player
**Bundle ID:** com.deezer.Deezer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=292738169">292738169</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/deezer-music-podcast-player/id292738169?uo=4">https://apps.apple.com/us/app/deezer-music-podcast-player/id292738169?uo=4</a>
**App Version:** 7.11.0
**Seller:** DEEZER SA
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/deezer-sa/id292738172?uo=4">© DEEZER SA</a>
**Supported Devices:** Watch4-Watch4, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/a3/e7/62/a3e762bb-7516-b158-662a-1b51d06e32a1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382374-8af07e00-9a62-11e9-9bf6-6226e2ae4106.png)

**Comment by Anuskuss** [comment] 2016-09-26 23:38
Needs update for -large method.

**Comment by 2Qt2beStr8** [comment] 2016-09-28 20:49
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18931749/c2450044-85cd-11e6-8b00-a4e6ba48ec1f.png)
https://cloud.githubusercontent.com/assets/20930745/18931749/c2450044-85cd-11e6-8b00-a4e6ba48ec1f.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18931769/d335468e-85cd-11e6-8f1e-f2114ec1bfcc.png

**Comment by BrokenCommander** [comment] 2016-09-28 22:40
Pointed corners (already made the icon but forgot to post it):
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/22012363/18899063/85aea4c4-8536-11e6-9129-0180bad45aa7.png)
https://cloud.githubusercontent.com/assets/22012363/18899063/85aea4c4-8536-11e6-9129-0180bad45aa7.png
___
Source:
https://cloud.githubusercontent.com/assets/22012363/18899064/85b4fbf8-8536-11e6-886b-d1de6975b0be.png

**Comment by XPEric** [comment] 2019-01-05 23:30
Needs update.

**Comment by XPEric** [comment] 2019-01-05 23:30
[DUPLICATE of #3935]
**App Name:** Deezer: Music & Podcast Player
**Bundle ID:** com.deezer.Deezer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=292738169">292738169</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/deezer-music-podcast-player/id292738169?mt=8&uo=4">https://itunes.apple.com/us/app/deezer-music-podcast-player/id292738169?mt=8&uo=4</a>
**App Version:** 7.1.1
**Seller:** DEEZER SA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/deezer-sa/id292738172?uo=4">© DEEZER SA</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/df/da/85/dfda857d-ad5f-4dc4-5da6-25db3fcaaf91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by XPEric** [comment] 2019-01-05 23:35
![deezer](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/50730320-9187e380-1118-11e9-84bf-6cf18550dc42.png)
https://user-images.githubusercontent.com/2313873/50730320-9187e380-1118-11e9-84bf-6cf18550dc42.png

___
Source:
https://user-images.githubusercontent.com/2313873/50730322-9e0c3c00-1118-11e9-82d0-42c4b56a4570.png

**Comment by 2Qt2beStr8** [comment] 2019-01-13 08:12
@dreamnet XPEric's icons are all to small

![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/51083025-f217b180-1712-11e9-9a81-572fb0eceffb.png)
https://user-images.githubusercontent.com/20930745/51083025-f217b180-1712-11e9-9a81-572fb0eceffb.png

Source:
https://user-images.githubusercontent.com/20930745/51083026-f47a0b80-1712-11e9-97cb-e5372e2aa644.png

**Comment by dreamnet** [comment] 2019-01-13 08:19
@2Qt2beStr8 Yes, you are right. I remade them on my website.

**Comment by dreamnet** [comment] 2019-06-29 09:09
Needs an update.

**Comment by 2Qt2beStr8** [comment] 2019-06-29 09:39
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60382374-8af07e00-9a62-11e9-9bf6-6226e2ae4106.png)
https://user-images.githubusercontent.com/20930745/60382374-8af07e00-9a62-11e9-9bf6-6226e2ae4106.png

Source:
https://user-images.githubusercontent.com/20930745/60382375-8cba4180-9a62-11e9-9de7-38a825771797.png

**Closed** 2019-06-29 11:20 UTC
