### ISSUE TITLE
NordVPN: VPN Fast & Unlimited

### ISSUE THREAD

**Issue by Trubbel** [glasklart/hd#5707] opened 2015-05-29 18:59 UTC
**App Name:** NordVPN: VPN Fast & Unlimited
**Bundle ID:** com.nordvpn.NordVPN
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=905953485">905953485</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nordvpn-vpn-fast-unlimited/id905953485?mt=8&uo=4">https://itunes.apple.com/us/app/nordvpn-vpn-fast-unlimited/id905953485?mt=8&uo=4</a>
**App Version:** 4.3.9
**Seller:** TEFINKOM & CO S.A
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tefinkom-co-s-a/id905953488?mt=8&uo=4">© Tefinkom & CO S.A.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/b4/9c/bc/b49cbcd8-78f9-59ea-f0be-4572225cc5b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58764459-7609f300-8567-11e9-911d-c6af8769d78f.png)

**Comment by ivanov007** [comment] 2015-05-31 19:58
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7903544/7d6cdb06-07a5-11e5-8dda-c26f28f7e1e1.png)
https://cloud.githubusercontent.com/assets/3090247/7903544/7d6cdb06-07a5-11e5-8dda-c26f28f7e1e1.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7903545/7dbe95a4-07a5-11e5-948e-ef2827cc0f24.png

**Comment by MagnaMike** [comment] 2015-05-31 20:15
@ivanov007 I wouldn't center it vertically?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/7903601/27078968-07b0-11e5-9369-a9e949317291.png)
https://cloud.githubusercontent.com/assets/2236254/7903601/27078968-07b0-11e5-9369-a9e949317291.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/7903603/2e4f35fe-07b0-11e5-89dc-b740e9956dd6.png

**Comment by dreamnet** [comment] 2015-05-31 20:59
@MagnaMike Jep. it looks better at the bottom.

**Comment by XPEric** [comment] 2019-06-02 14:32
Needs name and icon update.

[DUPLICATE of #5707]
**App Name:** NordVPN: VPN Fast & Unlimited
**Bundle ID:** com.nordvpn.NordVPN
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=905953485">905953485</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nordvpn-vpn-fast-unlimited/id905953485?mt=8&uo=4">https://itunes.apple.com/us/app/nordvpn-vpn-fast-unlimited/id905953485?mt=8&uo=4</a>
**App Version:** 4.3.9
**Seller:** TEFINKOM & CO S.A
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tefinkom-co-s-a/id905953488?mt=8&uo=4">© Tefinkom & CO S.A.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/b4/9c/bc/b49cbcd8-78f9-59ea-f0be-4572225cc5b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by XPEric** [comment] 2019-06-02 14:35
![tyt](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58762874-248b4500-8522-11e9-9b26-1770551d5a58.png)
https://user-images.githubusercontent.com/2313873/58762874-248b4500-8522-11e9-9b26-1770551d5a58.png

___
Source:
https://user-images.githubusercontent.com/2313873/58762870-1f2dfa80-8522-11e9-8abc-5a8f4b5c2c5b.png

**Comment by dreamnet** [comment] 2019-06-02 16:52
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58764459-7609f300-8567-11e9-911d-c6af8769d78f.png)
https://user-images.githubusercontent.com/2068130/58764459-7609f300-8567-11e9-911d-c6af8769d78f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58764466-86ba6900-8567-11e9-8f13-0e914e7c6c22.png

**Closed** 2019-06-02 16:59 UTC
