### ISSUE TITLE
Robinhood - $0 Commission Stock Trading

### ISSUE THREAD

**Issue by WaterTrooper** [glasklart/hd#5327] opened 2015-03-10 08:12 UTC
**App Name:** Robinhood - $0 Commission Stock Trading
**Bundle ID:** com.robinhood.release.Robinhood
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=938003185">938003185</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/robinhood-$0-commission-stock/id938003185?mt=8&uo=4">https://itunes.apple.com/us/app/robinhood-$0-commission-stock/id938003185?mt=8&uo=4</a>
**App Version:** 2.3.3
**Seller:** Robinhood Markets Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/robinhood-markets-inc./id938003184?uo=4>© Robinhood Markets, Inc.</a>
**Supported Devices:** iPad23G, iPhone5, iPhone4S, iPhone5c, iPadMini4G, iPhone6Plus, iPad2Wifi, iPadFourthGen4G, iPadMini, iPadThirdGen4G, iPhone5s, iPadFourthGen, iPhone4, iPadThirdGen, iPodTouchFifthGen, iPhone6
**Original Artwork:**
<img src="http://a1752.phobos.apple.com/us/r30/Purple5/v4/97/a9/e0/97a9e0ee-c57f-524d-de9d-a35bfcdf5ba0/mzl.udwlmroc.png" width="150" height="150" />
**Accepted Artwork:**
![@2x](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6609547/6299546e-c829-11e4-9202-b38154169662.png)

**Comment by WaterTrooper** [comment] 2015-03-10 08:12
BTW. I think I still have some invites is anyone wants. 😄

**Comment by pishit** [comment] 2015-03-10 13:17
Here is my try
![glasklart_ios7_icon_template - robinhood](https://cloud.githubusercontent.com/assets/11317341/6575566/1fbeefcc-c730-11e4-817a-118e85f6f00e.png)

**Comment by ivanov007** [comment] 2015-03-10 14:09
@pishit it looks good, there's just a few details, first you need to wait until the issue is marked as valid to post an icon and the post is not right, I've corrected your post so it shows the icon link and the preview template, you just need to port the source file (as link)

**Comment by ivanov007** [comment] 2015-03-10 14:09
@WaterTrooper I wold like a invite, how do I found you? or you find me?

**Comment by MagnaMike** [comment] 2015-03-10 17:50
@pishit The source file is incorrect. The source is a 1024x1024 image that represents the 78x78 area. If I made an icon with your source file, I would get this:
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6581288/502d12fa-c72c-11e4-85d7-b1278c621b06.png)

**Comment by MagnaMike** [comment] 2015-03-10 18:00
This would be the correct source for this icon:

![@2x](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6581501/bc6d5e1a-c72d-11e4-9615-6e78059c3c30.png)
https://cloud.githubusercontent.com/assets/2236254/6581501/bc6d5e1a-c72d-11e4-9615-6e78059c3c30.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6581500/b7601bce-c72d-11e4-9b73-45b1965b8809.png

**Comment by WaterTrooper** [comment] 2015-03-11 04:25
Send me an email. I have 3 Robinhood invites and it will give you an account right away. 

WaterTrooper@Gmail.com

**Comment by MagnaMike** [comment] 2015-03-12 00:01
It appears I made an error when I scaled the icon - the aspect ratio is off. Corrected:
![@2x](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6609547/6299546e-c829-11e4-9202-b38154169662.png)
https://cloud.githubusercontent.com/assets/2236254/6609547/6299546e-c829-11e4-9202-b38154169662.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6609545/5f45cb9e-c829-11e4-91f2-aafac615a6e3.png

**Closed** 2015-03-12 17:07 UTC
