### ISSUE TITLE
Speedtest by Ookla

### ISSUE THREAD

**Issue by ryjacs** [glasklart/hd#1947] opened 2013-03-22 04:23 UTC
**App Name:** Speedtest by Ookla
**Bundle ID:** com.ookla.speedtest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300704847">300704847</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/speedtest-by-ookla/id300704847?mt=8&uo=4">https://itunes.apple.com/us/app/speedtest-by-ookla/id300704847?mt=8&uo=4</a>
**App Version:** 4.1.2
**Seller:** Ookla
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ookla/id300704850?uo=4">© Ookla</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/07/45/9a/07459a8c-71bd-7e12-803d-290dd5ee948d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/51084096-f220ad00-1724-11e9-9a8a-01a0a1041875.png)

**Comment by Anuskuss** [comment] 2015-11-07 20:06
**New Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/ad/73/c1/ad73c161-b765-c682-39bd-195876de3f82/source/512x512bb.jpg" width="150" height="150" />

**Comment by dreamnet** [comment] 2015-11-12 21:35
@Anuskuss Not possible - I only can make it a bit bigger.
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/11131972/8df045ca-898d-11e5-8248-39753457bd17.png)
https://cloud.githubusercontent.com/assets/2068130/11131972/8df045ca-898d-11e5-8248-39753457bd17.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/11131980/9d3afca0-898d-11e5-8c34-4993cd500b68.png

**Comment by Anuskuss** [comment] 2015-11-14 05:29
You decide :)

**Comment by XPEric** [comment] 2019-01-05 23:14
Needs update

**Comment by XPEric** [comment] 2019-01-05 23:14
[DUPLICATE of #1947]
**App Name:** Speedtest by Ookla
**Bundle ID:** com.ookla.speedtest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300704847">300704847</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/speedtest-by-ookla/id300704847?mt=8&uo=4">https://itunes.apple.com/us/app/speedtest-by-ookla/id300704847?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** Ookla
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ookla/id300704850?uo=4">© Ookla</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/60/ff/b4/60ffb44c-e3f0-c6b0-f906-5991d38d641d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by XPEric** [comment] 2019-01-05 23:18
![speedtest](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/50730221-479dfe00-1116-11e9-930f-dcc50d417629.png)
https://user-images.githubusercontent.com/2313873/50730221-479dfe00-1116-11e9-930f-dcc50d417629.png

___
Source:
https://user-images.githubusercontent.com/2313873/50730220-4371e080-1116-11e9-9faa-1ef755e85400.png

**Comment by 2Qt2beStr8** [comment] 2019-01-13 10:19
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/51084096-f220ad00-1724-11e9-9a8a-01a0a1041875.png)
(https://user-images.githubusercontent.com/20930745/51084096-f220ad00-1724-11e9-9a8a-01a0a1041875.png

Source:
https://user-images.githubusercontent.com/20930745/51084097-f3ea7080-1724-11e9-80b4-7155f4f4d8e4.png

**Closed** 2019-01-20 11:46 UTC
