### ISSUE TITLE
DR Nyheder

### ISSUE THREAD

**Issue by andersmogensen** [glasklart/hd#4369] opened 2014-08-24 12:56 UTC
**App Name:** DR Nyheder
**Bundle ID:** dk.dr.nyheder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=398346158">398346158</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dr-nyheder/id398346158?uo=4">https://apps.apple.com/us/app/dr-nyheder/id398346158?uo=4</a>
**App Version:** 5.3.8
**Seller:** DR
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dr/id327331170?uo=4">© DR</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/17/e2/1a/17e21aa2-3da3-f1cb-e3cc-3d4620a3f6a3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66265398-0443fd80-e816-11e9-95cf-a3cf58e76564.png)

**Comment by cassio299** [comment] 2019-10-06 00:16
New Icon, please reopen for new issue

**Comment by cassio299** [comment] 2019-10-06 00:23
[DUPLICATE of #4369]

**App Name:** DR Nyheder
**Bundle ID:** dk.dr.nyheder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=398346158">398346158</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dr-nyheder/id398346158?uo=4">https://apps.apple.com/us/app/dr-nyheder/id398346158?uo=4</a>
**App Version:** 5.3.8
**Seller:** DR
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/dr/id327331170?uo=4">© DR</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/17/e2/1a/17e21aa2-3da3-f1cb-e3cc-3d4620a3f6a3/source/1024x1024bb.png" width="180" height="180" />

**Accepted Artwork:**

\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by cassio299** [comment] 2019-10-06 00:30
https://user-images.githubusercontent.com/28823252/66262453-b5c83c00-e7e0-11e9-8e6a-9debef1ef754.png

![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/28823252/66262453-b5c83c00-e7e0-11e9-8e6a-9debef1ef754.png

Source:

https://user-images.githubusercontent.com/28823252/66262479-4737ae00-e7e1-11e9-9660-4c4bc399d252.png

**Comment by dreamnet** [comment] 2019-10-06 06:48
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66265398-0443fd80-e816-11e9-95cf-a3cf58e76564.png)
https://user-images.githubusercontent.com/2068130/66265398-0443fd80-e816-11e9-95cf-a3cf58e76564.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66265402-132ab000-e816-11e9-9d18-d92b6688c923.png

**Closed** 2019-10-06 07:12 UTC
