### ISSUE TITLE
ESPN

### ISSUE THREAD

**Issue by J3D1-WARR10R** [glasklart/hd#660] opened 2013-02-06 01:41 UTC
**App Name:** ESPN
**Bundle ID:** com.espn.ScoreCenter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=317469184">317469184</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/espn/id317469184?mt=8&uo=4">https://itunes.apple.com/us/app/espn/id317469184?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** ESPN Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/espn/id317469187?uo=4>© ESPN</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/9b/e3/01/9be301ed-203e-54f2-17f6-a403e1024d26/mzl.tjttsuto.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10083820/59455bb6-6300-11e5-8172-2b975fe95a92.png)

**Comment by l8er4now** [comment] 2015-09-24 16:51
Can we do an updated icon?

[DUPLICATE of #660]
**App Name:** ESPN
**Bundle ID:** com.espn.ScoreCenter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=317469184">317469184</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/espn/id317469184?mt=8&uo=4">https://itunes.apple.com/us/app/espn/id317469184?mt=8&uo=4</a>
**App Version:** 4.5
**Seller:** ESPN Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/espn/id317469187?uo=4>© ESPN</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/9b/e3/01/9be301ed-203e-54f2-17f6-a403e1024d26/mzl.tjttsuto.png/0x0ss-85.jpg" width="150" height="150" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment] 2015-09-24 19:08
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10083820/59455bb6-6300-11e5-8172-2b975fe95a92.png)
https://cloud.githubusercontent.com/assets/2068130/10083820/59455bb6-6300-11e5-8172-2b975fe95a92.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10083840/6a73cbb6-6300-11e5-9b8b-823a2f815eb3.png

**Closed** 2015-09-24 19:30 UTC
